### ISSUE TITLE
Xodus escapes some caracters

### ISSUE THREAD

**Issue by simmljoe** [robopatrol/robopatrol-server#1]
Ich habe versucht JSON Strings direkt in die Xodus DB zu speichern. Als output erhalte ich nun bei einem get request: `{"attributes":"{\"someKey\":\"someValue\"}","jobname":"somename"}`

Ist es irgendwie möglich die zusätzlichen Anführungszeichen (") und backslashes() zu unterdrücken?

Das Problem kann folgendermassen nachvollzogen werden:
Server Starten und einen **POST** (Für Firefox z.B. mit [https://addons.mozilla.org/de/firefox/addon/rest-easy/](url) ) ausführen mit **MIME Type** `application/JSON`
**content** `{"jobname":"somename","attributes":{"someKey":"someValue"}}` 
auf [http://localhost:9998/schedule](url)

Danach (z.B. direkt über Addresszeile) au [http://localhost:9998/schedule/somename](url) zugreiffen (GET) um Output zu erhalten

@DeeVeX Bitte nicht aktuellsten Commit verwenden sondern [https://github.com/robopatrol/robopatrol-server/commit/3cae287ec6f5626f69d2b1e6bb467754b8882e54](url)

**Comment by chilloutman** [comment]
We propably _shouldn't_ put JSON strings straight into the database.

Consider using 'Entities'. Like in this example:
https://github.com/JetBrains/xodus/blob/master/samples/src/main/java/jetbrains/exodus/entitystore/PersistentStoreExample.java

**Comment by simmljoe** [comment]
@chilloutman That was not the problem. The problem was that i tried to put a JSON-Formated String to an JSON Object. If you do this you should not use 
`object.put("sometext", jsonFormatedString)`, but 
`object = new JSONObject(jsonFormatedString)` and then add object to another object. Otherwise the `.put` method will escape known caracters!

For JSON that's ok, but if we use more complex stores, we should consider Entities as you said.

Thanks to @joshfreak7 ! (and of course Thanks @chilloutman for the fast reply)

**Comment by chilloutman** [comment]
Ok. Let's leave this as a potential refactoring task (I think we're allowed to refactor, right? 😎).
