### ISSUE TITLE
Application not working in Docker context

### ISSUE THREAD

**Issue by DeeVeX** [robopatrol/robopatrol-server#6]
Tried to do GET and POST after running the robopatrol-server by starting the container (used `docker-compose build; docker-compose up`).
The tar, which `gradle build` produces is not the problem. I ran the server the same way the docker server would and it worked outside of the container.

**Comment by chilloutman** [comment]
Can you provide more info? What URL did you try?

If you're using docker-machine, make sure to use `docker-machine ip` and use that instead of `localhost`.

**Comment by DeeVeX** [comment]
I'm not using docker-machine. URL: http://localhost:9998/schedule.
Browser does sense that there should be a resource on this URL since i do not get any error messages from the browser. Do we have anyone in our team, who got that working who is not using docker-machine?
If i look at my docker container, the following exception is thrown as soon as i do a request:
(That was only one request)

> MultiException stack 1 of 2
> java.lang.ExceptionInInitializerError
>     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>     at org.glassfish.hk2.utilities.reflection.ReflectionHelper.makeMe(ReflectionHelper.java:1350)
>     at org.jvnet.hk2.internal.ClazzCreator.createMe(ClazzCreator.java:271)
>     at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:365)
>     at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
>     at org.glassfish.jersey.process.internal.RequestScope.findOrCreate(RequestScope.java:162)
>     at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
>     at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:765)
>     at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:704)
>     at org.glassfish.jersey.internal.inject.Injections.getOrCreate(Injections.java:172)
>     at org.glassfish.jersey.server.model.MethodHandler$ClassBasedMethodHandler.getInstance(MethodHandler.java:284)
>     at org.glassfish.jersey.server.internal.routing.PushMethodHandlerRouter.apply(PushMethodHandlerRouter.java:74)
>     at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:109)
>     at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:112)
>     at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:112)
>     at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:112)
>     at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:92)
>     at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:61)
>     at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197)
>     at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:318)
>     at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
>     at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
>     at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
>     at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
>     at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
>     at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
>     at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
>     at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
>     at org.glassfish.jersey.jdkhttp.JdkHttpHandlerContainer.handle(JdkHttpHandlerContainer.java:161)
>     at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
>     at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
>     at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
>     at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
>     at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
>     at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>     at java.lang.Thread.run(Thread.java:745)
> Caused by: org.mapdb.DBException$DataCorruption: Header checksum broken. Store was not closed correctly, or is corrupted
>     at org.mapdb.StoreDirectAbstract.fileHeaderCheck(StoreDirectAbstract.kt:99)
>     at org.mapdb.StoreDirect.<init>(StoreDirect.kt:93)
>     at org.mapdb.StoreDirect$Companion.make(StoreDirect.kt:48)
>     at org.mapdb.StoreDirect$Companion.make$default(StoreDirect.kt:47)
>     at org.mapdb.DBMaker$Maker.make(DBMaker.kt:392)
>     at ch.zhaw.robopatrol.store.RobopatrolStore.<init>(RobopatrolStore.java:27)
>     at ch.zhaw.robopatrol.store.RobopatrolStore.forClass(RobopatrolStore.java:19)
>     at ch.zhaw.robopatrol.res.Schedule.<clinit>(Schedule.java:18)
>     ... 41 more
> MultiException stack 2 of 2
> java.lang.IllegalStateException: Unable to perform operation: create on ch.zhaw.robopatrol.res.Schedule
>     at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:392)
>     at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
>     at org.glassfish.jersey.process.internal.RequestScope.findOrCreate(RequestScope.java:162)
>     at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
>     at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:765)
>     at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:704)
>     at org.glassfish.jersey.internal.inject.Injections.getOrCreate(Injections.java:172)
>     at org.glassfish.jersey.server.model.MethodHandler$ClassBasedMethodHandler.getInstance(MethodHandler.java:284)
>     at org.glassfish.jersey.server.internal.routing.PushMethodHandlerRouter.apply(PushMethodHandlerRouter.java:74)
>     at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:109)
>     at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:112)
>     at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:112)
>     at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:112)
>     at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:92)
>     at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:61)
>     at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197)
>     at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:318)
>     at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
>     at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
>     at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
>     at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
>     at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
>     at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
>     at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
>     at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
>     at org.glassfish.jersey.jdkhttp.JdkHttpHandlerContainer.handle(JdkHttpHandlerContainer.java:161)
>     at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
>     at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
>     at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
>     at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
>     at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
>     at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>     at java.lang.Thread.run(Thread.java:745)
> May 02, 2016 6:57:20 AM org.glassfish.jersey.internal.Errors logErrors
> WARNING: The following warnings have been detected: WARNING: Unknown HK2 failure detected:
> MultiException stack 1 of 2
> java.lang.ExceptionInInitializerError
>     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>     at org.glassfish.hk2.utilities.reflection.ReflectionHelper.makeMe(ReflectionHelper.java:1350)
>     at org.jvnet.hk2.internal.ClazzCreator.createMe(ClazzCreator.java:271)
>     at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:365)
>     at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
>     at org.glassfish.jersey.process.internal.RequestScope.findOrCreate(RequestScope.java:162)
>     at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
>     at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:765)
>     at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:704)
>     at org.glassfish.jersey.internal.inject.Injections.getOrCreate(Injections.java:172)
>     at org.glassfish.jersey.server.model.MethodHandler$ClassBasedMethodHandler.getInstance(MethodHandler.java:284)
>     at org.glassfish.jersey.server.internal.routing.PushMethodHandlerRouter.apply(PushMethodHandlerRouter.java:74)
>     at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:109)
>     at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:112)
>     at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:112)
>     at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:112)
>     at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:92)
>     at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:61)
>     at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197)
>     at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:318)
>     at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
>     at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
>     at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
>     at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
>     at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
>     at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
>     at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
>     at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
>     at org.glassfish.jersey.jdkhttp.JdkHttpHandlerContainer.handle(JdkHttpHandlerContainer.java:161)
>     at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
>     at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
>     at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
>     at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
>     at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
>     at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>     at java.lang.Thread.run(Thread.java:745)
> Caused by: org.mapdb.DBException$DataCorruption: Header checksum broken. Store was not closed correctly, or is corrupted
>     at org.mapdb.StoreDirectAbstract.fileHeaderCheck(StoreDirectAbstract.kt:99)
>     at org.mapdb.StoreDirect.<init>(StoreDirect.kt:93)
>     at org.mapdb.StoreDirect$Companion.make(StoreDirect.kt:48)
>     at org.mapdb.StoreDirect$Companion.make$default(StoreDirect.kt:47)
>     at org.mapdb.DBMaker$Maker.make(DBMaker.kt:392)
>     at ch.zhaw.robopatrol.store.RobopatrolStore.<init>(RobopatrolStore.java:27)
>     at ch.zhaw.robopatrol.store.RobopatrolStore.forClass(RobopatrolStore.java:19)
>     at ch.zhaw.robopatrol.res.Schedule.<clinit>(Schedule.java:18)
>     ... 41 more
> MultiException stack 2 of 2
> java.lang.IllegalStateException: Unable to perform operation: create on ch.zhaw.robopatrol.res.Schedule
>     at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:392)
>     at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
>     at org.glassfish.jersey.process.internal.RequestScope.findOrCreate(RequestScope.java:162)
>     at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
>     at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:765)
>     at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:704)
>     at org.glassfish.jersey.internal.inject.Injections.getOrCreate(Injections.java:172)
>     at org.glassfish.jersey.server.model.MethodHandler$ClassBasedMethodHandler.getInstance(MethodHandler.java:284)
>     at org.glassfish.jersey.server.internal.routing.PushMethodHandlerRouter.apply(PushMethodHandlerRouter.java:74)
>     at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:109)
>     at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:112)
>     at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:112)
>     at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:112)
>     at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:92)
>     at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:61)
>     at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197)
>     at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:318)
>     at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
>     at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
>     at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
>     at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
>     at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
>     at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
>     at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
>     at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
>     at org.glassfish.jersey.jdkhttp.JdkHttpHandlerContainer.handle(JdkHttpHandlerContainer.java:161)
>     at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
>     at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
>     at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
>     at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
>     at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
>     at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>     at java.lang.Thread.run(Thread.java:745)

**Comment by chilloutman** [comment]
I see. It looks like we can't create the db file inside the container. In my testing, I already had one created.

I think we have to map a volume inside the container to a directly outside the container. I think that should do it.
